version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "9090:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=app_user9090
      - POSTGRES_PASSWORD=app_pass9090
      - POSTGRES_DB=root